name: "Netlify Deployment"

on: 
  push:
  pull_request:
    branches: [main, develop]

defaults: 
  run:
    working-directory: frontend/mms-Admin
  
jobs:
  test_deployment: 
    runs-on: ubuntu-latest

    steps:
      - name: "code checkout"
        uses: actions/checkout@v3
        with:
          node-version: 16

      - name: "install dependencies"
        run: npm install
        with:
          node-version: 16
      - run: npm run build

      - name: "deploy to netlify"
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: lR3JK0dXeHUkIdby570JzBZE-UJ4X4nE-KoxqZXbkDI
          NETLIFY_SITE_ID: 8680e251-87b0-45fe-a86c-5889ce94c008
        with: 
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'

      - run: echo "Deployment Successful"